Pp 40 UI convert patient agenda js to tsx
informatici/openhospital-portal pull request #23
Opened 2023-07-20 16:21 UTC by Serdf3rISF

2023-11-02 13:51 UTC, Serdf3rISF commented
In addition to converting patient agenda to tsx, the code has been cleaned

2023-11-02 14:02 UTC, mwithi commented on docker-compose-ops.yaml
> +      device: /home/s3r/htdocs/OH/OH_PP_SERDF3R/openhospital-portal/patient-portal/sql
Please revert this change

2023-11-02 14:03 UTC, mwithi commented on patient-portal-ui/src/components/utility/patient/analyses_data/input_data/Iarterial_pressure.tsx
> +        console.log(rif)
maybe comment this

2023-11-02 14:08 UTC, mwithi commented on patient-portal-ui/src/components/utility/patient/analyses_data/input_data/Iarterial_pressure.tsx
> +            console.log(rif.maxValue);
All these log could be commented out

2023-11-02 14:09 UTC, mwithi commented on patient-portal-ui/src/datajs/DeafutlAllData.tsx
> +const url_0 = 'http://localhost:18080/api/'; // --- uncomment to develop locally
toggle these two comments

2023-11-02 14:10 UTC, mwithi commented on patient-portal-ui/src/datajs/DeafutlAllData.tsx
> +const url_0 = 'http://localhost:18080/api/'; // --- uncomment to develop locally
the correct form is `api-develop.ohpp.local`

2023-11-02 14:11 UTC, mwithi commented on patient-portal-ui/src/datajs/DeafutlAllData.tsx
> +    let response = await fetch('http://develop-api.ohpp.local:18080/api/admin/users');
the correct form is `api-develop.ohpp.local`, but I think you can reuse url_0 here

2023-11-02 14:11 UTC, mwithi commented on patient-portal-ui/src/datajs/DeafutlAllData.tsx
> +const url_0 = 'http://localhost:18080/api/'; // --- uncomment to develop locally
we should find a way to externalize the url_0 in a config class

2023-11-02 14:12 UTC, mwithi commented on patient-portal-ui/src/datajs/DeafutlAllData.tsx
> +    // return data;
we can remove commented lines if we don't need them, we can always retrieve from commits history in case

2023-11-02 14:12 UTC, mwithi commented on patient-portal-ui/src/datajs/DeafutlAllData.tsx
>      console.log(res_all);
do we need these logs?

2023-11-02 14:13 UTC, mwithi commented on patient-portal-ui/src/pages/patient/PatientAgenda.tsx
> +      });
Do we need these logs or we can comment them?

2023-11-02 14:13 UTC, mwithi commented on patient-portal-ui/src/pages/patient/PatientAgenda.tsx
> +      < Box sx={{ mt: 14, width: 1 }}>
```suggestion
      <Box sx={{ mt: 14, width: 1 }}>
```

2023-11-02 14:14 UTC, mwithi requested changes
Small changes required

2023-11-02 15:43 UTC, mwithi commented on patient-portal-ui/src/datajs/DeafutlAllData.tsx
> +
this is for development, the correct url_0 for production is:
```suggestion
const url_0 = 'http://api-develop.ohpp.local:18080/api/
// const url_0 = 'http://localhost:18080/api/'; //uncomment for development
```

2023-11-14 21:23 UTC, closed without merging

2023-11-14 21:23 UTC, mwithi commented
Superseded by https://github.com/informatici/openhospital-portal/pull/25